### PR TITLE
replace portfinder with newport

### PR DESCRIPTION
**Pull request by harttle**
Fixes: #325 and #215

### CODE REVIEW

**Comment by derhuerst** [comment]
By using `newport`, `http-server` loses the ability to specify a specific port (which is VERY handy imo) and fallback to the next available. Also, the defacto standard port for adhoc/dev HTTP servers is `8080`.

**Comment by harttle** [comment]
I think it's faster and also valid to let Node.js server to use a random clean port :)

**Comment by derhuerst** [comment]
Still, this is a regression. As some people use this for serving static files permanently, `http-server` will  effectively be broken for them.

**Comment by xuexb** [comment]
This is one of my ideas : Default port is `8080`, if the error is random.

```js
process.on('uncaughtException', function (err) {
  if (err.syscall === 'listen' && err.port === 8080) {
    console.log(colors.red('\n8080 port is occupied, will randomly generate a new port!\n'));
    newport(function (err, port) {
      if (err) { throw err; }
      listen(port);
    });
  }
});

if (!port) {
  portfinder.basePort = 8080;
  portfinder.getPort(function (err, port) {
    if (err) { throw err; }
    listen(port);
  });
}
else {
  listen(port);
}
```
image

Thanks~

**Comment by derhuerst** [comment]
> This is one of my ideas : Default port is `8080`, if the error is random.

> If set up over the port, when being given an error I think it is reasonable. If no port is set, the next port is randomly enabled when the `8080` is occupied for the service to start

I'd personally rather like the opposite: I would like to specify a port (and have it fail if the port is used). In case I didn't care about a specific port and just want *any* port, I would pass `--find-port`, which uses `newport`.

This would work out using *only* `newport`, without catching via `uncaughtException`, and without being a regression over the previous behavior.

Af few notes on your implementation:

- Using `process.on('uncaughtException', cb)` is considered dangerous & bad practice. Note how `process.once` would be more appropriate.
- `console.log(colors.red(` should be replaced by something that writes to `stderr` (instead of `stdout`) and sets the exit code to non-`0`.
- Your code uses `portfinder` & `newport`. Why not use one of them?

**Comment by xuexb** [comment]
Above is just one of my ideas, really lack of thinking~  Thank you very much~

> I'd personally rather like the opposite: I would like to specify a port (and have it fail if the port is used). In case I didn't care about a specific port and just want any port, I would pass `--find-port`, which uses `newport`.

This is good~

**Comment by BigBlueHat** [comment]
I'm assisting @indexzero in catching up with the backlog of PRs here.

@derhuerst I'm 👍 on the approach you've outlined, and would be happy to accept a PR.

@harttle would you be in support of the approach outlined in https://github.com/indexzero/http-server/pull/332#issuecomment-268971162

I'm not keen to loose the ability to define a specific port, but having the *option* to fallback / have one found for me, sounds fab!

**Comment by harttle** [comment]
@BigBlueHat OK, I'll make a PR this week later.

**Comment by harttle** [comment]
I've implemented the `--find-port` option. Please ping this thread if there's still anything I can help.

**Comment by BigBlueHat** [comment]
@harttle just took this for a spin locally (bash in Windows 10) and it worked like a charm!

I'm going to give this a bit for others to test, then possibly add it to the v0.10.0 release.

Much thanks!
🎩

**Comment by harttle** [comment]
I just find out that upgrade the `portfinder` fixes this issue without any regression. The last commit would be better.

**Comment by BigBlueHat** [comment]
@harttle oh. Even better. Mind squashing this PR into just the necessary code?

**Comment by harttle** [comment]
It's Ok, there is only one commit actually, since I reset it before.☺️

**Comment by BigBlueHat** [comment]
@harttle looks like this is *just* the `portfinder` update, correct? If that's the case, that means this code doesn't currently provide the `--find-port` option. Would you mind adding that to this PR?

Thanks!

**Comment by BigBlueHat** [comment]
@harttle I'm going to close this one--as it's a bit tangled now--in favor of the newly opened #363 which is specifically about the `--find-port` param.

I've upgraded `portfinder` in  989fa1c by way of keeping things up to date.

Thanks for taking the lead on this feature!
🎩

**Pull request closed without merging**
