### PR TITLE
fix opener call

### LINKED ISSUE #271: kit-es2016 -> http://localhost//127.0.0.1:8080
I am currently looking into the Aurelia framework, and when I follow the instructions at http://aurelia.io/docs.html#/aurelia/framework/latest/doc/article/getting-started and do the `http-server -o -c-1`, my Safari (9.1) opens a new tab on "http://localhost//127.0.0.1:8080", which Safari fails to handle. That URL of course is completely wrong. I have tried it on three different versions of Mac OS X.
I reported the problem to Aurelia, https://github.com/aurelia/framework/issues/410, but they said it seems like an issue with the **http-server** module rather than Aurelia itself. Therefore I report it here.

### PR DESCRIPTION
**Pull request by derhuerst**
This seems to fix #271 and #264. Possible duplicate of #250, #234 and #231.

### CODE REVIEW

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by derhuerst** [comment]
bump.

**Comment by mcqj** [comment]
Don't understand why this is closed as the problem still exists in 0.9 and the PR doesn't appear to have been merged.

**Comment by derhuerst** [comment]
@mcqj When has this been closed?

**Comment by mcqj** [comment]
My bad - I saw it had been closed on Nov 11 and didn't notice it was re-opened. I though it had been lost in when merging other PRs. I see now that it was indeed still open.

**Comment by derhuerst** [comment]
bump.

**Comment by menangen** [comment]
This commit solve problem on Safari:
https://github.com/craigmichaelmartin/http-server/commit/1779827b911d7149d9918c1ba4881a583f77b841

**Comment by thornjad** [comment]
Fixed in #374

**Pull request closed without merging**
