### PR TITLE
Proxy error handling

### PR DESCRIPTION
**Pull request by sjohnsonaz**
I added a small bit of error handling to the proxy section.  It causes the server to return a 503 status, rather than exit.

### CODE REVIEW

**Comment by apixandru** [comment]
I'm having this exact same problem now, the server just crashes with regular chrome usage.
If the http server proxies /request1 to http://otherserver/request and i go and access /request1 and refresh a couple of times without letting the request go through, the http-server crashes.

**Comment by rafaelsales** [comment]
It feels like the owner has to add more maintainers to the project so that it scales, or it will become a ghost town

**Comment by BigBlueHat** [comment]
This generally looks good. It needs some tests and the whitespace changes removed. Once those are added, this seems like a good addition. Thanks!

**Comment by thornjad** [comment]
Closing in favor of the non-crashing logging in #477

**Pull request closed without merging**
