### PR TITLE
Fixed the high severity vulnerability (https://npmjs.com/advisories/830)

### LINKED ISSUE #461: Prototype Override Protection Bypass Vulnerability
See https://app.snyk.io/test/npm/http-server/0.11.1

Also wrote up an issue on union's github https://github.com/flatiron/union/issues/59

To resolve, wait for union to update their version of qs or remove the dependency

### LINKED ISSUE #480: .wasm (application/wasm) is served with charset
this should not happen.

### LINKED ISSUE #512: file descriptor leak on aborted non-range request
See, https://github.com/jfhbrook/node-ecstatic/pull/246

### LINKED ISSUE #518: Upgrade to latest ecstatic
As of right now, ecstatic is at version 4.1.0, but we're still requiring only 3.3.0 on master. We need to make sure there are no breaking changes and upgrade, probably requiring `^4.x.x`.

This will fix #461 and #512.

### PR DESCRIPTION
**Pull request by miherlosev**
Fixes #518, fixes #461, fixes #512, fixes #480

### CODE REVIEW

**Comment by thornjad** [comment]
The failing tests may have to do with ecstatic's major version bump

**Comment by jfhbrook** [comment]
You guys may want to find a new module, I don't plan on maintaining ecstatic going forward

I'm working on a proper announcement, but a little behind on the curve.

**Comment by thornjad** [comment]
@jfhbrook thanks for the heads up! We'll still get up to the latest ecstatic for now, but I might start looking around then. Are you thinking of looking for maintainers, or more like stepping away entirely?

**Comment by thornjad** [comment]
I've been investigating a little, and it looks like this upgrade entirely breaks http-server, it won't serve anything, except for displaying the root directory listing. This may have something to do with mime types and/or charsets, but that's as far as I've gotten.

**Comment by jfhbrook** [comment]
mimetype and charset handling got rewritten https://github.com/jfhbrook/node-ecstatic/pull/240

**Comment by jonkoops** [comment]
@jfhbrook Did you remove older versions of `ecstatic`? As it looks like it's been removed and now `npx http-server .` fails with the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for ecstatic@^3.0.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget
npm ERR! notarget It was specified as a dependency of 'http-server'
npm ERR! notarget
```

@thornjad I believe this completely breaks `http-server` right now, any way I can help out?

**Comment by thornjad** [comment]
jfhbrook/node-ecstatic#255

**Comment by thornjad** [comment]
@jonkoops the issue with this PR is that for some reason it causes http-server to simply not serve anything, but without throwing errors. I haven't had enough time to look at it, but so far I can't find the problem.

ecstatic's [changelog](https://github.com/jfhbrook/node-ecstatic/blob/master/CHANGELOG.md) is a good starting point, probably. It includes an upgrade to v2 of [node-mime](https://github.com/broofa/node-mime) which _may_ be an issue.

**Comment by thornjad** [comment]
@BigBlueHat are you available? You may have a good perspective on this

**Comment by thornjad** [comment]
@miherlosev because this is causing weird breaking changes, and because of #521, I'm going to close this PR and move your commit into a new branch to make it easier for others to help track down the breaking changes.

**Comment by BigBlueHat** [comment]
> @BigBlueHat are you available? You may have a better perspective on this than me

Catching up, and will help how I'm able.

**Comment by thornjad** [comment]
@BigBlueHat the immediate fire should be put out by jfhbrook/node-ecstatic#256, so this may at least me less important

**Comment by BigBlueHat** [comment]
@thornjad the mime module changes specifically (though not exclusively) were part of the hold-up earlier with moving to newer versions of ecstatic. There were several major point releases across several modules and many of them shifted core APIs or deprecated/removed APIs this code depends on. Modern software development tail chasing, I guess...

**Pull request closed without merging**
