### PR TITLE
fix to treat -o argument as url not command

### LINKED ISSUE #197: Running from package.json with -o flag fails
I have this code to preview a production build:

    "scripts": {
        "server": "http-server -o build/production"
    }

Without the `-o` flag, `http-server` is started, but with the flag, I get an `Error: spawn EACCES`.

### PR DESCRIPTION
**Pull request by craigmichaelmartin**
closes #197 #231

### CODE REVIEW

**Comment by smarts** [comment]
This is a duplicate of #250. I'm not sure why this PR even exists... @craigmichaelmartin are you trying to steal credit from @sqlwwx?

**Comment by craigmichaelmartin** [comment]
I know, I listed it as such in my commit message, and I have spent time referencing the three open PRs (including the one you reference) back to two issues. My hope was to make the threshold of complexity as low as possible for @indexzero by providing that leg work. I ended up forking this repo for my own projects to fix this and decided after the fact to make this PR since the one you reference is comprised of multiple commits - one of which doesn't pass ci. I asked the author to rebase his commits (again, to make the friction for merging as low as possible). Trust me, I don't care about credit for this. I spent the first week giving feedback to the open PRs (including the one you reference). I just want a fix merged and am trying to provide the leg-work and common best-practices for commits in order for indexzero to have no barriers for fixing this :P

**Comment by smarts** [comment]
Fair enough. It's a shame that such a simple issue is taking so long to get fixed :cry:

**Comment by craigmichaelmartin** [comment]
Yeah. Feel free to reference/fork my fork. I tagged a release v0.10.0 with this fix.

Given Github's new [merge and squash](https://github.com/blog/2141-squash-your-commits) option, I'll close this and hope #250 is merged.

**Pull request closed without merging**
