### PR TITLE
fixbug with -o [path]    Open browser window after starting the server

### PR DESCRIPTION
**Pull request by sqlwwx**
fixbug with -o [path]    Open browser window after starting the server

### CODE REVIEW

**Comment by andywer** [comment]
+1
Tested it locally and works for me, too, now (Chrome 49 on OSX). Would appreciate it if it could be merged soon :)

**Comment by craigmichaelmartin** [comment]
I think squashing your commits would help :) Also, is this a duplicate of #234?

**Comment by thornjad** [comment]
Fixed in #374

**Comment by thornjad** [comment]
Sorry, closed the wrong PR

**Comment by thornjad** [comment]
@sqlwwx would you rebase this onto the current `master`? Otherwise I can take this over if you'd like.

**Comment by sqlwwx** [comment]
@thornjad updated

**Comment by philipjmurphy** [comment]
This doesn't appear to be in the latest release: http-server@0.11.1 - would be nice to get this fix released.

**Pull request merged**
