### PR TITLE
Add missing slashes

### PR DESCRIPTION
**Pull request by CatTail**

### CODE REVIEW

**Comment by CatTail** [comment]
@indexzero Is this project still alive? Can anyone merge this simple PR?

**Comment by BigBlueHat** [comment]
@CatTail the `protocol` variable already includes the slashes:
https://github.com/CatTail/http-server/blob/e9c82393e1c0d14ee15016390b2a46fb37a72e5f/bin/http-server#L126

Did you see that output without them someplace? If so, where did you see them missing?

Thanks!

**Comment by CatTail** [comment]
Sorry I can't reproduce the issue

**Comment by BigBlueHat** [comment]
NP @CatTail ! Thanks for checking.

**Pull request closed without merging**
