### PR TITLE
The SSL CA root certificate path parameter

### PR DESCRIPTION
**Pull request by waltom**
Please add path parameter to ssl ca root certificate.
Following change in file http-server solves the problem.

  if (ssl) {
    options.https = {
      cert: argv.C || argv.cert || 'cert.pem',
      key: argv.K || argv.key || 'key.pem',
      **ca: argv.R || argv.root || 'ca.pem' *\*  /** this line is needed */
    };
  }

### CODE REVIEW

**Comment by derhuerst** [comment]
[Just a minor note] You could have [rebased](https://git-scm.com/docs/git-rebase) your PR to make it less noisy.

**Comment by BigBlueHat** [comment]
@waltom is this line indeed the only thing that needs adding?

```js
*ca: argv.R || argv.root || 'ca.pem' * / this line is needed */
```

If so, would you mind making a new PR (branch off of `master`) and submitting just that change?

Bonus open source contributor points for also adding it to the README. 😄 

This current PR's a bit of a tangled mess, so starting fresh is likely best.

Appreciate it!

**Comment by dilignt** [comment]
When will this CA root certificate parameter be available in master?  I can't see it in the source.

**Comment by BigBlueHat** [comment]
@dilignt the idea of this PR is fine, but this branch is tangled up with old code, and I'd (greatly) prefer a simple commit done with no history tangles done against master.

If you're interested in extracting the new content on this branch and sending a new PR, it would help get this to a merge-able state.

Cheers.

**Comment by thornjad** [comment]
@waltom I'm not sure what's happening here, it looks like branches may have gotten mixed up. This PR is attempting to merge `master` into `common-style`, and because the PR branch is `master`, all commits to `master` are triggering Travis builds. 

Because of the branch weirdness, I'm going to close this PR so Travis stops triggering necessarily. If you're still interested in contributing, please do open a new PR!

**Pull request closed without merging**
