### PR TITLE
Open browser with URL provided in -o [path]

### PR DESCRIPTION
**Pull request by hancharou**
#231 Fix to use url in -o [path]

### CODE REVIEW

**Comment by craigmichaelmartin** [comment]
Would you mind squashing your commits?

**Comment by hancharou** [comment]
The commits were squashed. It's very safe change.

**Comment by hancharou** [comment]
I added logger info for url it's opening.
And moved 'Hit CTRL-C to stop the server' to the end.

**Comment by thornjad** [comment]
Closing in favor of #250 due to the simpler style

**Pull request closed without merging**
