### PR TITLE
add livereload

### PR DESCRIPTION
**Pull request by tamamadesu**
add livereload module 

How to work ?

First, install the LiveReload browser plugins by visiting http://help.livereload.com/kb/general-use/browser-extensions. and:
> $  http-server -w

### CODE REVIEW

**Comment by indexzero** [comment]
@tamamadesu thank you for your contribution. Your PR is not passing tests because it fails lint. Try running `npm test` and making the changes. The list of errors is [also in the TravisCI job](https://travis-ci.org/indexzero/http-server/jobs/71944802)

**Comment by indexzero** [comment]
@tamamadesu cool feature! I'm going to wait until more people request it before considering adding it in.

**Comment by evanplaice** [comment]
:+1: @indexzero consider me added to the request list

Express and [insert server middleware] is overkill for devs working on SPAs that don't require a data back-end, or pull data from an api client-side via AJAX.

Http-server is perfect for developing SPAs, livereload support is the last missing piece preventing me from ditching express on projects where I don't need to server-side app.

**Comment by piotrwitek** [comment]
+1, I'm feeling the same here, the last missing piece, for now just using alternatives

**Comment by evanplaice** [comment]
@piotrwitek Take a look at live-server. It basically works the same as http-server but provides live-reload and open-browser by default.

**Comment by piotrwitek** [comment]
@evanplaice thanks a lot for your suggestion :), actually I'm using jspm-server as an alternative, a fork of live-server.
Still I think that livereload is now kinda standard, and should be implemented anyway to keep up with the competition :)

**Comment by gtcdevop** [comment]
@indexzero I would appreciate that feature man

**Pull request closed without merging**
