### PR TITLE
Add baseDir option and pass-through to ecstatic

### PR DESCRIPTION
**Pull request by idmontie**
Upgrade ecstatic to version 3.0.0. Use ecstatic's baseDir option
to set a base directory.

See #390

### CODE REVIEW

**Comment by BigBlueHat** [comment]
Thanks for this PR, @idmontie.

One concern, though, is that `http-server` will still tie up whatever pot it's assigned to (i.e. 8080), but won't be able to serve anything else except what's under `baseDir`.

I fear it would encourage the wrong exceptions, such as "oh good! now `http-server` can serve my `/blog/` directory, and my other apps can serve everything else!"--which would not be the case...

What are your thoughts on avoiding that misconception?

**Comment by BigBlueHat** [comment]
#139 and #63 also feel related and worth a read.

**Comment by idmontie** [comment]
@BigBlueHat That's true, I didn't think about that.

In my case, I'm emulating a production folder structure on my local system, so files are usually pushed up to a subdirectory on a server, while on my local machine, they simply live in a build folder.

I can see where the confusion lies. Maybe I can update the documentation/options docs to reflect that the port will be used, even though the files may be served with a prefix.

**Comment by BigBlueHat** [comment]
That use case makes sense. If you can make that clear enough in the docs, then this is probably worth having--certainly others face the same scenario.

Thanks!

**Comment by hikumealan** [comment]
Any ETA on this? I have the same use case and would really like to see this feature.

**Comment by yashha** [comment]
Thats good if you want to test the page routing when you know it will be served on a subpath in the futuer.

**Comment by kolisko** [comment]
+1

**Comment by thornjad** [comment]
Alright, @idmontie's #395 and @jesseditson's #294 have a one-line difference. I'm going to go with #294 because it came first

**Comment by MaximSagan** [comment]
> Alright, @idmontie's #395 and @jesseditson's #294 have a one-line difference. I'm going to go with #294 because it came first

@thornjad This issue was closed, but neither of the PRs you mentioned were ever merged. As #294 (the one you said you'd go with) has gone stale with merge conflicts since then, I have rebased the it into #837.

**Comment by hairinwind** [comment]
> 

Can this be merged? We do need this feature. Thanks!

**Pull request closed without merging**
